---
booktitle: Proceedings of the Eleventh International Conference on Grammatical Inference
publisher: JMLR Workshop and Conference Proceedings
volume: 21
year: '2012'
logoright: basic_files/ICGI2012-logo.png
month: 0
start: 2012-09-05
end: 2012-09-08
published: 2012-08-16
shortname: ICGI 2012
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: HeinzICGI2012
abstract: ''
tex_title: 
title: Proceedings of Machine Learning Research
editor:
- given: Jeffrey
  family: Heinz
- given: Colin
  family: Higuera
- given: Tim
  family: Oates
description: |
  Proceedings of the Eleventh International Conference on Grammatical Inference
    Held in University of Maryland, College Park, MD, USA on 05-08 September 2012

  Published as Volume 21 by the Proceedings of Machine Learning Research on 16 August 2012.

  Volume Edited by:
    Jeffrey Heinz
    Colin Higuera
    Tim Oates

  Series Editors:
    Neil D. Lawrence
date_str: 05--08 Sep
url: http://proceedings.mlr.press
baseurl: "/v21"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v21
bibtex_copy: true
email: ''
conference:
  name: International Conference on Grammatical Inference
  url: 
  location: University of Maryland, College Park, MD, USA
  dates:
  - 2012-09-05
  - 2012-09-06
  - 2012-09-07
  - 2012-09-08
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v21.bib
