---
booktitle: Proceedings of the Eleventh International Conference on Grammatical Inference
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
publisher: PMLR
volume: 21
year: '2012'
logoright: basic_files/ICGI2012-logo.png
month: 0
start: 2012-09-05
end: 2012-09-08
published: 2012-08-16
shortname: ICGI 2012
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: HeinzICGI2012
cycles: false
editor:
- given: Jeffrey
  family: Heinz
- given: Colin
  family: Higuera
- given: Tim
  family: Oates
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Eleventh International Conference on Grammatical Inference
    Held in University of Maryland, College Park, MD, USA on 05-08 September 2012

  Published as Volume 21 by the Proceedings of Machine Learning Research on 16 August 2012.

  Volume Edited by:
    Jeffrey Heinz
    Colin Higuera
    Tim Oates

  Series Editors:
    Neil D. Lawrence
date_str: 05--08 Sep
url: http://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v21"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v21
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: International Conference on Grammatical Inference
  url: 
  location: University of Maryland, College Park, MD, USA
  dates:
  - 2012-09-05
  - 2012-09-06
  - 2012-09-07
  - 2012-09-08
  number: 11
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
